version: 0.2
env:

  secrets-manager:
    SECRET_KEY: "codepipeline:SECRET_KEY"
    NEW_ACCESS_KEY: "codepipeline:NEW_ACCESS_KEY"
    ACCESS_KEY: "codepipeline:ACCESS_KEY"
    NEW_SECRET_KEY: "codepipeline:NEW_SECRET_KEY"
    AOA_ACCESS_KEY: "codepipeline:AOA_ACCESS_KEY"
    AOA_SECRET_KEY: "codepipeline:AOA_SECRET_KEY"

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd blin
      - echo install process started
      - npm install && npm install -g @angular/cli

  build:
    commands:
       - echo testing...
       - ng build --configuration production --build-optimizer --aot
       - ls
       - pwd
       - ls
       - pwd
       
  post_build:
    commands:
       - aws configure set aws_access_key_id $AOA_ACCESS_KEY
       - aws configure set aws_secret_access_key $AOA_SECRET_KEY
       - aws s3 sync dist/ s3://$S3_BUCKET_BUILDTWIN/ --region eu-central-1 --acl public-read --exclude 'get-started/*'
       - aws cloudfront create-invalidation --distribution-id EPLSHPTTCJVLG --paths "/index.html" 
